name: app_ascs
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.3
  google_sign_in: ^6.1.5
  http: ^0.13.3
  http_parser: ^4.0.2
  path_provider: ^2.1.1
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  amplify_flutter: ^2.6.1
  amplify_storage_s3: ^2.6.1
  amplify_core: ^2.6.1
  amplify_auth_cognito: ^2.6.1
  amplify_api: ^2.6.1
  connectivity_plus: ^6.0.3

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Functional Programming
  dartz: ^0.10.1

  # Dependency Injection
  get_it: ^7.6.0

  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.0.0
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/imagenes/foco_auscultacion.jpg
    - assets/config/medical_config.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/Corazon.png"
  adaptive_icon_background: "#84A0E3"
  adaptive_icon_foreground: "assets/icons/Corazon.png"
